version: "3.8"

services:
  backend:
    image: 529646246979.dkr.ecr.ap-southeast-2.amazonaws.com/awstodo-backend:${TAG}
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      REDIS_PORT: 6379
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      ACCESS_EXPIRE: ${ACCESS_EXPIRE}
      REFRESH_EXPIRE: ${REFRESH_EXPIRE}
      REDIS_HOST: ${REDIS_HOST}
      AWS_REGION: ${AWS_REGION}

  nginx:
    image: 529646246979.dkr.ecr.ap-southeast-2.amazonaws.com/awstodo-nginx:${TAG}
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
