plugin: amazon.aws.aws_ec2
regions:
  - ap-southeast-2

filters:
  tag:Project: awstodo
  tag:Environment: production
  instance-state-name: running

hostnames:
  - instance-id

groups:
  webservers: "tags.Role == 'web'"
  monitoring: "tags.Role == 'monitoring'"
