name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Validate structure
        run: |
          set -e
          test -d backend || (echo "backend missing" && exit 1)
          test -d frontend || (echo "frontend missing" && exit 1)
          test -f docker-compose.yml || (echo "docker-compose.yml missing" && exit 1)

      - name: Install backend deps
        run: |
          cd backend
          npm ci

  cd:
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #  OIDC
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Test AWS identity
        run: aws sts get-caller-identity

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      #  Build & Push backend
      - name: Build & Push backend
        run: |
          IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/awstodo-backend
          docker build -t $IMAGE:${{ github.sha }} ./backend
          docker push $IMAGE:${{ github.sha }}

      #  Build & Push nginx
      - name: Build & Push nginx
        run: |
          IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/awstodo-nginx
          docker build -t $IMAGE:${{ github.sha }} ./frontend
          docker push $IMAGE:${{ github.sha }}

      #  Upload docker-compose (version + latest)
      - name: Upload compose to S3 (versioned)
        run: |
          BUCKET=${{ secrets.S3_BUCKET }}

          aws s3 cp docker-compose.yml \
            s3://$BUCKET/deploy/docker-compose-${{ github.sha }}.yml

          aws s3 cp docker-compose.yml \
            s3://$BUCKET/deploy/docker-compose.yml
      - name: Capture Current Tag for Rollback
        id: prev_info
        run: |
          PREV_TAG=$(aws ssm send-command \
            --instance-ids ${{ secrets.WEBSERVER1ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands": ["docker inspect --format=\"{{index .Config.Image}}\" awstodo-backend | cut -d: -f2"]}' \
            --query "CommandInvocations[0].CommandPlugins[0].Output" \
            --output text | tr -d '\r\n')
          echo "PREVIOUS_TAG=${PREV_TAG:-latest}" >> $GITHUB_ENV
      # Deploy via SSM
      - name: Deploy to Webservers via SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.WEBSERVER1ID }}" "${{ secrets.WEBSERVER2ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy version ${{ github.sha }}" \
            --parameters '{
              "commands": [
                "set -e",
                "export HOME=/home/ec2-user",
                "cd /home/ec2-user/AWStodo",
                "aws s3 cp s3://${{ secrets.S3_BUCKET }}/deploy/docker-compose.yml .",
                "aws ssm get-parameters-by-path --path \"/todoapp/\" --with-decryption --query \"Parameters[*].[Name,Value]\" --output text | sed \"s|^/todoapp/||\" | awk '\''{print $1 \"=\" $2}'\'' > .env",
                "echo \"TAG=${{ github.sha }}\" >> .env",
                "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com",
                "docker compose pull",
                "docker compose up -d --remove-orphans",
                "docker image prune -f",
                "rm .env"
              ]
            }'
      - name: Health Check and Rollback
        run: |
          URL="http://${{ secrets.LB_DNS }}/health"
          
          check_health() {
            local url=$1
            local label=$2
            echo "Checking $label..."

            for i in $(seq 1 8); do
              BODY=$(curl -s --max-time 5 "$url")
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$url")

              echo "Attempt $i: HTTP $STATUS | Body: $BODY"

              if [ "$STATUS" = "200" ] && echo "$BODY" | grep -q '"database":"UP"'; then
                echo "$label is Healthy!"
                return 0
              fi

              sleep 10
            done

            echo "$label FAILED after 8 attempts"
            return 1
          }

          if check_health "$URL" "NEW VERSION"; then
            echo "Deployment Successful!"
            exit 0
          else
            echo "New version failed! Triggering Rollback to Tag: ${{ env.PREVIOUS_TAG }}..."

            aws ssm send-command \
              --instance-ids "${{ secrets.WEBSERVER1ID }}" "${{ secrets.WEBSERVER2ID }}" \
              --document-name "AWS-RunShellScript" \
              --parameters "commands=[
                \"set -e\",
                \"cd /home/ec2-user/AWStodo\",
                \"aws s3 cp s3://${{ secrets.S3_BUCKET }}/deploy/docker-compose-${{ env.PREVIOUS_TAG }}.yml docker-compose.yml\",
                \"aws ssm get-parameters-by-path --path /todoapp/ --with-decryption --query 'Parameters[*].[Name,Value]' --output text | sed 's|^/todoapp/||' | sed 's|\\t|=|' > .env\",
                \"echo TAG=${{ env.PREVIOUS_TAG }} >> .env\",
                \"docker compose up -d --remove-orphans\",
                \"sleep 5\",
                \"rm -f .env\"
              ]"
              }'

            echo "Waiting 10s for rollback version..."
            sleep 10

            if check_health "$URL" "PREVIOUS VERSION"; then
              echo "Rollback success."
              exit 1
            else
              echo "CRITICAL: Rollback failed!"
              exit 1
            fi
          }